library:
  source-dirs: src
copyright: 2020 Zhongyang Xia
maintainer: zhongyang.xia@mailutoronto.ca
dependencies:
- containers
- text
- text-icu
- base >= 4.7 && < 5
name: emojilang
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Zhongyang Xia
github: XIAZY/emojilang
license: MIT
executables:
  emojilang-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emojilang
description: Please see the README on GitHub at <https://github.com/githubuser/emojilang#readme>
