library:
  source-dirs: src
copyright: 2020 XIAXY
maintainer: i@mechanus.io
dependencies:
- containers
- text
- text-icu
- base >= 4.7 && < 5
name: emojilang
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: XIAZY
github: XIAZY/emojilang
license: MIT
executables:
  emojilang-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emojilang
description: Please see the README on GitHub at <https://github.com/xiazy/emojilang#readme>
